import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir, platform } from "node:os";
import { join, resolve } from "node:path";
import { parse as parseYaml } from "yaml";

export type BootstrapSource = "explicit" | "env" | "binding" | "preset";

export type KeyDecision = {
  key: string;
  source: BootstrapSource;
};

type PresetEntry = { match?: string; key?: string };
type PresetsFile = { projects?: PresetEntry[] };

export const DEFAULT_PRESETS_PATH = join(homedir(), ".jira-agent", "presets.yaml");

export type DecideProjectKeyOptions = {
  explicitKey?: string;
  env?: NodeJS.ProcessEnv;
  /**
   * The key this user has bound to this workspace, already looked up. Passed
   * in rather than read here so this function stays a pure ordering of
   * explicit sources.
   */
  bindingKey?: string;
  presetsPath?: string;
};

/**
 * Decide a project key from explicit sources only - JAM never guesses a Jira
 * project from a folder or repo name. Order: `--project` flag, then
 * `JAM_PROJECT_KEY`, then this user's binding for the workspace, then a
 * matching entry in the legacy preset file. Returns undefined when none
 * apply, which the caller must treat as "cannot decide safely".
 *
 * Flag over environment over persisted, because what someone typed for this
 * run should beat what a shell exported, which should beat what was recorded
 * some time ago.
 */
export function decideProjectKey(
  root: string,
  options: DecideProjectKeyOptions = {},
): KeyDecision | undefined {
  const explicit = options.explicitKey?.trim();
  if (explicit) return { key: explicit, source: "explicit" };

  const envKey = (options.env ?? process.env).JAM_PROJECT_KEY?.trim();
  if (envKey) return { key: envKey, source: "env" };

  const bindingKey = options.bindingKey?.trim();
  if (bindingKey) return { key: bindingKey, source: "binding" };

  const preset = findPresetKey(root, options.presetsPath ?? DEFAULT_PRESETS_PATH);
  if (preset) return { key: preset, source: "preset" };

  return undefined;
}

function findPresetKey(root: string, presetsPath: string): string | undefined {
  if (!existsSync(presetsPath)) return undefined;

  let parsed: PresetsFile;
  try {
    parsed = (parseYaml(readFileSync(presetsPath, "utf8")) ?? {}) as PresetsFile;
  } catch {
    // A broken preset file should not crash bootstrap - just skip it.
    return undefined;
  }

  const target = normalizePath(root);
  for (const entry of parsed.projects ?? []) {
    if (!entry.match || !entry.key) continue;
    if (normalizePath(entry.match) === target) return entry.key;
  }
  return undefined;
}

/** Windows paths are case-insensitive; every other platform is compared as-is. */
export function normalizePath(p: string): string {
  const resolved = resolve(p);
  return platform() === "win32" ? resolved.toLowerCase() : resolved;
}

const GENERATED_HEADER = "# Generated by JAM. Safe to commit.\n";

/**
 * Writes the minimal `.jira-agent/project.yaml`. Only the key is set - every
 * other field is left to the schema's built-in defaults so this file stays
 * legible and merge-friendly.
 */
export function writeBootstrapConfig(root: string, key: string): string {
  const dir = join(root, ".jira-agent");
  mkdirSync(dir, { recursive: true });
  const path = join(dir, "project.yaml");
  writeFileSync(path, `${GENERATED_HEADER}version: 1\n\nproject:\n  key: ${key}\n`, "utf8");
  return path;
}
